[build]
  command = "npm install --force && npm install --save-dev typescript && NODE_ENV=production npm run build"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--force" 